language: ruby
rvm:
  - 1.9.2
bundler_args: --without development
env:
  - TEST_SUITE=test:units GOVUK_APP_DOMAIN=test.gov.uk RUBYOPT="-rpsych"
  - TEST_SUITE=test:functionals GOVUK_APP_DOMAIN=test.gov.uk RUBYOPT="-rpsych"
  - TEST_SUITE=test:integration GOVUK_APP_DOMAIN=test.gov.uk RUBYOPT="-rpsych"
  - TEST_SUITE=cucumber CUCUMBER_FORMAT=progress GOVUK_APP_DOMAIN=test.gov.uk RUBYOPT="-rpsych"
  - TEST_SUITE=test:javascript GOVUK_APP_DOMAIN=test.gov.uk RUBYOPT="-rpsych"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database progress_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake $TEST_SUITE
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mkdir clean-uploads
branches:
  except:
    - master
    - release
notifications:
  email: false
